### ISSUE TITLE
Could not find method google() for arguments [] on repository container

### ISSUE THREAD

**Issue by PasinduDineth** [react-native-camera/react-native-camera#1530]
Hi all,
I am having this error after i install react native camera. Can anyone help me. I have changed build.gradle dependency classpath to 3 also. But nothing is working. Any ideas?
error - 
A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.

**Comment by Adwich** [comment]
What version of react, react-native and react-native-camera do you use ?

**Comment by ahmedXabdeen** [comment]
Hi, @Adwich 
I'm running through this same issue, my react and react-native versions are:

react-native-cli: 2.0.1
react-native: 0.55.3
react: 16.3.1
react-native-camera: 1.1.2

**Comment by code-by** [comment]
same issue
react-native-cli: 2.0.1
react-native: 0.55.3
react-native-camera: 1.1.2

**Comment by 24** [comment]
set gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

```

set build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}


```

**Comment by lech-code-monkey** [comment]
I have the same error: 
![wk7lmbqkqe5si lzlth 7 t](https://user-images.githubusercontent.com/38339414/39507258-bd08eef4-4e0f-11e8-8aad-971241ac3d73.png)

**Comment by PasinduDineth** [comment]
@24 after editing as you told, im getting this error,
 Android dependency 'com.android.support:support-v4' has different version for the compile (23.0.1) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution
any help?

**Comment by ma3dau** [comment]
@PasinduDineth it can be solved by excluding "com.android.support" from react-native-camera implementation in `/android/app/build.gradle`
```
implementation (project(':react-native-camera')) {
        exclude group: "com.android.support"
}
```

**Comment by jgfidelis** [comment]
@ma3dau Beware that if you exclude the support lib and not add it for compilation correctly on the build.gradle, your app will crash when taking a picture.

**Comment by 24** [comment]
@PasinduDineth  
I spent 2 hours learning react native and android .
 I was stupid  , learned to be a shit.
So, I had to learn swift. ..
I gave up   ........

so ,i don't know   answer ...

**Comment by velvetrain** [comment]
@PasinduDineth 
This worked for me :  Make sure your react native version first , if you are using react-native < 0.40 then 
```npm install --save react-native-camera@0.4```. If react-native < 0.40 then do ```npm install --save react-native-camera@0.6``` .  Link the react-native-camera using ```react-native link react-native-camera```

- Follow the steps below after linking.
    - in node_modules\react-native-camera\index.js 
          1. removed PropTypes from ```import React, { Component, PropTypes } from 'react';```
          2. add ```import PropTypes from 'prop-types';```

-  in package.json.
         1. add in "dependencies"  ```"prop-types": "^15.6.0"```

**Comment by x3388638** [comment]
@PasinduDineth 
I use the code @24 provided but get the same problem
however it was solved by adding the following code in `android/build.gradle`
```
subprojects {
  project.configurations.all {
     resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.android.support'
              && !details.requested.name.contains('multidex') ) {
           details.useVersion "27.1.0"
        }
     }
  }
}
```

and changing `compileSdkVersion` & `buildToolsVersion` in `android/app/build.gradle`
```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.0"
    ...
```

finally, it works

modules version
```
{
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-camera": "^1.1.2",
    "react-native-qrcode-scanner": "^1.0.1",
}
```

**Comment by 841660202** [comment]
who tell me how to solve it?

**Comment by ma3dau** [comment]
I solve it, but maybe I have some specific case of use. I use `react-native-camera` as part of `react-native-qrcode-scanner`, so I don't need to take a picture and other camera functionality. For me helped @24 solution, but next error "different version for the compile" I couldn't solve with @x3388638 suggestions. My solution for `app/build.gradle` is:
```
compile (project(':react-native-camera')) {
      exclude group: "com.android.support", module: 'support-v4'
}
```
my modules version is same as @x3388638.
my top level `build.grande` is:
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        google()
        maven {
           url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        google()
    }
}
```
gradle/wrapper/gradle-wrapper.properties`
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```
If excluding `com.android.support` is a bad way and will be a better solution I'll try it. For my issue (reading barcodes) this setup works as well.

**Comment by lech-code-monkey** [comment]
@x3388638Thanks a lot, you have solved my problem successful

**Comment by FidelisChimombe** [comment]
@x3388638 thank you so much, you are life saver

**Comment by flyher** [comment]
@x3388638 the code doesn't work and build failed
@ma3dau build success but i got the white screen

**Comment by sibelius** [comment]
https://github.com/react-native-community/react-native-camera/issues/1561#issuecomment-389588786

**Comment by kkusanagi** [comment]
@ma3dau after change the to grade 4.1, and add google() under buildscript and all project.
Still get "Could not find method google() for arguments [] for root android folder."

Any solution?

**Comment by pstanton** [comment]
I've managed to get it working by making numerous changes some listed here, others found all over the web. I also use react-native-maps which has conflicting requirements. This is a major problem and requires immediate attention.

**Comment by kkusanagi** [comment]
I'm using react-native-camera@0.10 version for com.android.tools.build:gradle:2.2.+ which is quite stable for that version.

Once update the gradle, build version, react-native-camera, build.gradle, the whole system just crash. and don't know how to fix it. Really need some technical support / advice on how to upgrade properly.

By following android official migrate steps, only fix the latest react-native version, but for other plugin, all just crash.

Anyone who can create a blog about how to upgrade version would be helpful.

**Comment by Enigma10** [comment]
Hey Guys , My error got fixed with  combination of @24 and @x3388638  solutions. :) .

**Comment by mgiacopu** [comment]
@ma3dau your changes make the app compile but when I try to open the scanner it crashes without errors... I still don't get why the first error showed up.

**Comment by mgiacopu** [comment]
Instead, a combination of @24 and @x3388638 codes gives the final solution.
Now it works like a charm.
Thank you guys! Thumbs up!

**Comment by blogdaren** [comment]
@kk412027247  tks for your final solution with combination @24 and @x3388638 codes,  it really works well.

**Comment by bbeckk** [comment]
This solves the issue: https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md

**Comment by sospedra** [comment]
@kk412027247 comment should be on the official docs! Many thanks! Saved my day <3

**Comment by gokujy** [comment]
I am getting the same error:
Could not find method google() for arguments [] on repository container
Solve: I'm working on firebase crud and i installed angularfire2 and firebase plugin both.
So i uninstall firebase and error solved, i mean this error coming because conflict.

**Comment by gabrielbabierra** [comment]
Anyone have the same issue as mine after @kk412027247 's compiled edition changes. I have a build succesful but when i run my terminal i have an error:

_Bundling `index.android.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/Users/Cyberland/Desktop/AttApp"_
